import os
import sys

# use evaluation given by whoiswho
current_dir = os.path.abspath(os.path.dirname(__file__))
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, parent_dir)

from whoiswho.evaluation.SNDeval import evaluate

if __name__ == '__main__':
    
    # NOTE: prediction generated by demo.py is "./out/res.json"
    # You need to change the filename manually
    print('evaluate on train')
    predict = os.path.join(current_dir, './out/res_bond_train.json')
    ground_truth = os.path.join(current_dir, './dataset/data/v2/src/train/train_author.json')
    evaluate(predict, ground_truth)


    print('evaluate on valid')
    predict = os.path.join(current_dir, './out/res_bond_valid.json')
    ground_truth = os.path.join(current_dir, './dataset/data/v2/src/sna-valid/sna_valid_author_ground_truth.json')
    evaluate(predict, ground_truth)

    print('evaluate on test')
    predict = os.path.join(current_dir, './out/res_bond_test.json')
    ground_truth = os.path.join(current_dir, './dataset/data/v2/src/sna-test/sna_test_author_ground_truth.json')
    evaluate(predict, ground_truth)

    # evaluate on train
    # Average Pairwise F1: 0.746
    # evaluate on valid
    # Average Pairwise F1: 0.900
    # evaluate on test
    # Average Pairwise F1: 0.917